
if (CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
	set(TARGET_COMPILER_MSVC 1)
elseif (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
	set(TARGET_COMPILER_CLANG 1)
elseif (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
	set(TARGET_COMPILER_GCC 1)
else()
	message(WARNING "Unsupported Compiler: ${CMAKE_CXX_COMPILER_ID}")
	message(WARNING "Will continue configuration assuming GCC")
	set(TARGET_COMPILER_GCC 1)
endif()
