
if (CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
	set(TARGET_COMPILER_MSVC 1)
elseif (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
	set(TARGET_COMPILER_CLANG 1)
elseif (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
	set(TARGET_COMPILER_GCC 1)
else()
	message(FATAL_ERROR "Unsupported Compiler: ${CMAKE_CXX_COMPILER_ID}")
endif()

list (FIND CMAKE_CXX_COMPILE_FEATURES "cxx_std_11" _index)
if (${_index} GREATER -1)
	set(TARGET_COMPILER_SUPPORTS_CXX11 1)
	set(TARGET_COMPILER_HIGHEST_STD_SUPPORTED 11)
endif()

list (FIND CMAKE_CXX_COMPILE_FEATURES "cxx_std_14" _index)
if (${_index} GREATER -1)
	set(TARGET_COMPILER_SUPPORTS_CXX14 1)
	set(TARGET_COMPILER_HIGHEST_STD_SUPPORTED 14)
endif()

list (FIND CMAKE_CXX_COMPILE_FEATURES "cxx_std_17" _index)
if (${_index} GREATER -1)
	set(TARGET_COMPILER_SUPPORTS_CXX17 1)
	set(TARGET_COMPILER_HIGHEST_STD_SUPPORTED 17)
endif()

