function(FILE2C INFILE VARNAME OUTFILE)
  file(READ ${INFILE} HEXFILE HEX)
  string(LENGTH ${HEXFILE} XRSLEN)
  set(HEXPOS 0)
  file(WRITE ${OUTFILE} "\"")
  while(${HEXPOS} LESS ${XRSLEN})
    string(SUBSTRING ${HEXFILE} ${HEXPOS} 2 HEXBYTE)
    file(APPEND ${OUTFILE} "\\x${HEXBYTE}")
    math(EXPR HEXPOS "${HEXPOS} + 2")
    math(EXPR LPOS "${HEXPOS} % 32")
    if(NOT ${LPOS})
      FILE(APPEND ${OUTFILE} "\"\n\"")
    endif(NOT ${LPOS})	
  endwhile(${HEXPOS} LESS ${XRSLEN})
  file(APPEND ${OUTFILE} "\"\n")
endfunction(FILE2C)

# execute the function
FILE2C(${INFILE} ${VARNAME} ${OUTFILE})
