
#ifndef SEARCH_TYPE_H_
#define SEARCH_TYPE_H_

/*
** Schwarzenberg: added SEARCH_LITERAL_WORD .. SEARCH_REGEX_NOCASE
*/
enum SearchType {
	SEARCH_LITERAL,
	SEARCH_CASE_SENSE,
	SEARCH_REGEX,
	SEARCH_LITERAL_WORD,
	SEARCH_CASE_SENSE_WORD,
	SEARCH_REGEX_NOCASE,
};

#endif
